export const FETCH_APP_RECEIVES = 'FETCH_APP_RECEIVES'
export const FETCH_APP_RECEIVE_BY_ID = 'FETCH_APP_RECEIVE_BY_ID'
export const ADD_APP_RECEIVE = 'ADD_APP_RECEIVE'
export const UPDATE_APP_RECEIVE = 'UPDATE_APP_RECEIVE'
export const REMOVE_APP_RECEIVE = 'REMOVE_APP_RECEIVE'

// ----------------------------------------------------------------

export const FETCH_ACCOUNT_APP_RECEIVES = 'FETCH_ACCOUNT_APP_RECEIVES'
export const FETCH_ACCOUNT_APP_RECEIVE_BY_ID = 'FETCH_ACCOUNT_APP_RECEIVE_BY_ID'
export const ADD_ACCOUNT_APP_RECEIVE = 'ADD_ACCOUNT_APP_RECEIVE'
export const UPDATE_ACCOUNT_APP_RECEIVE = 'UPDATE_ACCOUNT_APP_RECEIVE'
export const REMOVE_ACCOUNT_APP_RECEIVE = 'REMOVE_ACCOUNT_APP_RECEIVE'

// ----------------------------------------------------------------

export const FETCH_SUPPLIER_APP_RECEIVES = 'FETCH_SUPPLIER_APP_RECEIVES'
export const FETCH_SUPPLIER_APP_RECEIVES_CONFIRMED = 'FETCH_SUPPLIER_APP_RECEIVES_CONFIRMED'
export const FETCH_SUPPLIER_APP_RECEIVES_DELIVERED = 'FETCH_SUPPLIER_APP_RECEIVES_DELIVERED'
export const SET_SEPPLIER_APP_RECEIVE_IN_THE_WAY = 'SET_SEPPLIER_APP_RECEIVE_IN_THE_WAY'
export const SET_SEPPLIER_APP_RECEIVE_DELIVERED = 'SET_SEPPLIER_APP_RECEIVE_DELIVERED'
